# Generated by Django 2.2.7 on 2019-11-09 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zip',
            name='summary',
            field=models.TextField(default='Thanks!'),
        ),
    ]
