# Generated by Django 2.2.7 on 2019-11-13 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zip', '0002_zip_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zip',
            name='summary',
        ),
        migrations.AddField(
            model_name='zip',
            name='county',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='zip',
            name='district',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zip',
            name='name',
            field=models.TextField(blank=True),
        ),
    ]
