# Generated by Django 2.2.7 on 2019-11-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zip', '0003_auto_20191112_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zip',
            name='code',
        ),
        migrations.AddField(
            model_name='zip',
            name='zip_code',
            field=models.IntegerField(default=0),
        ),
    ]
