# Generated by Django 2.2.7 on 2019-11-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zip', '0004_auto_20191116_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='rep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.TextField()),
                ('l_name', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='zip',
            name='name',
        ),
    ]
