# Generated by Django 2.2.7 on 2019-11-16 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zip', '0005_auto_20191116_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zip',
            old_name='district',
            new_name='congressional_district',
        ),
        migrations.RenameField(
            model_name='zip',
            old_name='zip_code',
            new_name='zcta',
        ),
    ]
