# Generated by Django 2.2.7 on 2019-11-20 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zip', '0007_auto_20191116_2245'),
    ]

    operations = [
        migrations.DeleteModel(
            name='district',
        ),
        migrations.DeleteModel(
            name='rep',
        ),
        migrations.DeleteModel(
            name='zip',
        ),
    ]
