# Generated by Django 2.2.7 on 2019-11-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='district',
            fields=[
                ('congressional_district', models.IntegerField(default=0)),
                ('zcta', models.IntegerField(default=0, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='rep',
            fields=[
                ('zip', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('f_name', models.TextField()),
                ('l_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='zip',
            fields=[
                ('zip', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('county', models.TextField(default='')),
            ],
        ),
    ]
