# Generated by Django 2.2.7 on 2019-12-12 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KentuckyProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Zip', models.IntegerField(max_length=5)),
                ('District', models.IntegerField()),
                ('CongressDistrict', models.TextField()),
                ('First_Name', models.TextField()),
                ('Last_Name', models.TextField()),
            ],
        ),
    ]
