# Generated by Django 2.2.7 on 2019-12-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kentuckyproject',
            name='Zip',
            field=models.IntegerField(),
        ),
    ]
