# Generated by Django 2.2.7 on 2019-11-27 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='zip',
            new_name='zipcodes',
        ),
    ]
