# Generated by Django 2.2.7 on 2019-11-22 21:59

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20191122_1612'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='district',
            managers=[
                ('congressional_district', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='district',
            name='congressional_district',
        ),
        migrations.RemoveField(
            model_name='district',
            name='zcta',
        ),
        migrations.AddField(
            model_name='district',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
