# Generated by Django 2.2.7 on 2019-11-28 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20191127_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='zcta',
            new_name='zip',
        ),
    ]
