# Generated by Django 2.2.7 on 2019-12-13 03:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20191212_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='kentuckyproject',
            name='Message',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
