# Generated by Django 2.2.7 on 2019-12-06 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20191127_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rep',
            old_name='zip',
            new_name='district',
        ),
    ]
