# Generated by Django 2.2.7 on 2019-12-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_kentuckyproject_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Csv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip', models.IntegerField()),
                ('primary_city', models.TextField()),
                ('county', models.TextField()),
                ('area_codes', models.CharField(max_length=5)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
    ]
