# Generated by Django 2.2.7 on 2019-11-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20191122_1659'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='district',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='district',
            name='id',
        ),
        migrations.AddField(
            model_name='district',
            name='congressional_district',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='district',
            name='zcta',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
