# Generated by Django 2.2.7 on 2019-12-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_csv'),
    ]

    operations = [
        migrations.CreateModel(
            name='KyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Outline_Img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
