# Generated by Django 2.2.7 on 2019-12-08 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20191206_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reps2000',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.IntegerField()),
                ('F_Name', models.TextField()),
                ('L_Name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reps2010',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.IntegerField()),
                ('F_Name', models.TextField()),
                ('L_Name', models.TextField()),
            ],
        ),
    ]
