# Generated by Django 2.2.7 on 2019-12-09 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_reps2000_reps2010'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reps2000',
        ),
        migrations.DeleteModel(
            name='Reps2010',
        ),
    ]
