# Generated by Django 2.2.7 on 2019-12-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_kyimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyimage',
            name='Outline_Img',
        ),
        migrations.AddField(
            model_name='kyimage',
            name='outlineImg',
            field=models.ImageField(default='null', upload_to=''),
        ),
    ]
