# Generated by Django 2.2.7 on 2019-12-16 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_auto_20191215_0303'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KentuckyProject',
            new_name='zipUser',
        ),
        migrations.DeleteModel(
            name='KyImage',
        ),
    ]
