# Generated by Django 2.2.7 on 2020-01-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_auto_20191215_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='mainData',
            fields=[
                ('Zip', models.IntegerField(primary_key=True, serialize=False)),
                ('district', models.IntegerField()),
                ('CongressDistrict', models.IntegerField()),
                ('First_Name', models.TextField(max_length=50)),
                ('Last_Name', models.TextField(max_length=50)),
            ],
        ),
    ]
