# Generated by Django 2.2.7 on 2020-01-18 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_maindata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Csv',
        ),
        migrations.DeleteModel(
            name='zipUser',
        ),
    ]
